### ISSUE TITLE
Adding new bindings is a destructive operation

### ISSUE THREAD

**Issue by mikeraimondi** [terraform-google-modules/terraform-google-iam#11]
Version 1.0.0

When used with `mode = "authoritative"`, when adding a new binding the module will sometimes attempt to delete one or more of the existing bindings. It then attempts to re-create them. The deletion events occur before any of the creation events and the delay between deletion and creation of bindings can be on the order of minutes.

This is problematic when used on production systems. The time between bindings being deleted and re-created is long enough that live workloads could experience IAM permission errors.

Ideally, adding new bindings would be a purely additive operation. Alternatively, if the delay between deletion and creation of bindings could be constrained to seconds instead of minutes, the risk to production systems would be minimized.

**Comment by morgante** [comment]
Unfortunately this is a constraint of how lists currently work in Terraform which we *should* be able to fix in Terraform 0.12.

**Comment by lokeshjawane** [comment]
I was trying to do the same and manage access using Terraform module. But we face the issue when we were running the TF script 2nd time and it was about to delete few resources. But right now there is no fix for it.

But using `authoritative` mode can save your life and you'll not have any user access destroy and creation lag. But again you just have to define only single module block in main.tf and keep adding users list in existing binding or define new binding with new role. I hope by `0.12` version will fix this issue.

**Comment by alexkonkin** [comment]
> 
> 
> I was trying to do the same and manage access using Terraform module. But we face the issue when we were running the TF script 2nd time and it was about to delete few resources. But right now there is no fix for it.
> 
> But using `authoritative` mode can save your life and you'll not have any user access destroy and creation lag. But again you just have to define only single module block in main.tf and keep adding users list in existing binding or define new binding with new role. I hope by `0.12` version will fix this issue.

I can not reproduce this scenario neither for terraform 0.11.13 (providers v. 1.20) nor for the v. 0.12.0 (providers v. 2.7) for the both versions the scenario is: 
- use the example that is supplied with the module (folder) 
- set the mode to authoritative 
- create a set of 10 service accounts 
- execute the script 1-st time as is with all mandatory variables a) execute script again (no modifications) result a: no changes to the state 

b) copy-paste to the bindings a set of 5 service accounts, etc. 
"serviceAccount:delete-me10@project1-243507.iam.gserviceaccount.com", 
"serviceAccount:delete-me5@project1-243507.iam.gserviceaccount.com", 
apply the changes from 
b) result b: modification operation is applied, deletion was not present in the script output 
c) change a number of dummy service account 
    records in bindings for Edit/View and apply the script result c: only modification operation was used during this operation 

Conclusion: 
I can not reproduce this behavior with the scenario 
above for the both versions (0.11 and 0.12)

Could you please illustrate the reported behavior
with the example that is based on one of the samples in the /examples folder (folder etc.)?

Thank you.

**Comment by aaron-lane** [comment]
@mikeraimondi @lokeshjawane can either of you provide an example which reproduces this issue?

**Comment by vitali-shcharbin** [comment]
Having pretty similar problem, when you have a bindings list:
```
bindings = {
    "roles/<role>" = [
        ...
    ]

    "roles/<role>" = [
       ...
    ]
```

Trying to add new role, will destroy and recreate all roles. It might be not reproducible if you have few roles, but if you have more than 10, it almost all the time. As I understood because root cause is  how bindings are sorted.
