### ISSUE TITLE
Release 6.3.0: Blocks of type "condition" are not expected here.

### ISSUE THREAD

**Issue by susovanpanja** [terraform-google-modules/terraform-google-iam#112]
Terraform v0.12.28
+ provider.google v3.29.0
IAM module version: 6.3.0

On Terraform validate:
----------------------------------------------------------------------------------------------
Error: Unsupported block type

  on .terraform/modules/organization-iam-bindings/modules/organizations_iam/main.tf line 36, in resource "google_organization_iam_binding" "organization_iam_authoritative":
  36:   dynamic "condition" {

Blocks of type "condition" are not expected here.

Error: Unsupported block type

  on .terraform/modules/organization-iam-bindings/modules/organizations_iam/main.tf line 54, in resource "google_organization_iam_member" "organization_iam_additive":
  54:   dynamic "condition" {

Blocks of type "condition" are not expected here.

Error: Unsupported block type

  on .terraform/modules/prod-folder/modules/folders_iam/main.tf line 36, in resource "google_folder_iam_binding" "folder_iam_authoritative":
  36:   dynamic "condition" {

Blocks of type "condition" are not expected here.

Error: Unsupported block type

  on .terraform/modules/prod-folder/modules/folders_iam/main.tf line 54, in resource "google_folder_iam_member" "folder_iam_additive":
  54:   dynamic "condition" {

Blocks of type "condition" are not expected here.

----------------------------------------------------------------------------------------------
If I use the version 6.2 in the code it is working perfectly fine and I am not using any conditions.

My sample code Not working:
----------------------------------------------------------------------------------------------

module "organization-iam-bindings" {
  source        = "terraform-google-modules/iam/google//modules/organizations_iam"
  organizations = [var.org_id]
  mode          = "additive"
  bindings      = var.org_iam_bindings
}

----------------------------------------------------------------------------------------------

My sample code working:
----------------------------------------------------------------------------------------------
module "organization-iam-bindings" {
  source        = "terraform-google-modules/iam/google//modules/organizations_iam"
  version = "= 6.2"
  organizations = [var.org_id]
  mode          = "additive"
  bindings      = var.org_iam_bindings
}

----------------------------------------------------------------------------------------------

**Comment by morgante** [comment]
Can you try with the latest GCP provider (3.38.0)?

**Comment by bharathkkb** [comment]
@morgante looks like it was [GA with 3.30.0 ](https://github.com/hashicorp/terraform-provider-google/blob/master/CHANGELOG.md#3300-july-13-2020) should we add a `required_providers` to lock this?

**Comment by morgante** [comment]
@bharathkkb Yes let's add it.
