### ISSUE TITLE
Do not use authoritative mode in examples

### ISSUE THREAD

**Issue by FridayPush** [terraform-google-modules/terraform-google-iam#117]
At multiple clients individuals working with Terraform that are of limited experience are copying the examples block and modifying it to fit their use case. The default use of `authoritative=true` has caused massive headaches multiple times. To clarify demonstrating it's there is beneficial, but please consider the volume of users that will copy/paste without fully understanding the implications of their actions. Yes the users should understand the module, but it would still be appreciated. 

This is primarily an enhancement and an quality of life change if possible. Thanks.

**Comment by morgante** [comment]
The default is actually `additive` mode and that's what our main examples show. Could you point to which examples are adding this confusion?

**Comment by FridayPush** [comment]
Thanks, here are a few examples that I found:
https://github.com/terraform-google-modules/terraform-google-iam/tree/master/modules/subnets_iam
https://github.com/terraform-google-modules/terraform-google-iam/tree/master/modules/pubsub_topics_iam
https://github.com/terraform-google-modules/terraform-google-iam/tree/master/modules/organizations_iam
https://github.com/terraform-google-modules/terraform-google-iam/tree/master/modules/kms_crypto_keys_iam

Are a few that show examples in Authoritative. I'm primarily referring to the Read Me's example usage.

**Comment by morgante** [comment]
Thanks! Do you think you could open a PR to remove the authoritative line from them?

**Comment by FridayPush** [comment]
Will do.
