### ISSUE TITLE
setting IAM project owner role fails.

### ISSUE THREAD

**Issue by sherifkozman** [terraform-google-modules/terraform-google-iam#120]
While creating a fresh new project and adding a gmail user ID as a project owner through IAM role "roles/owner", request fails with the following error :

Error: Request "Create IAM Members roles/owner user:xxxxx@gmail.com for \"project \\\"xxxx\\\"\"" returned error: Error applying IAM policy for project "es-bernasos": Error setting IAM policy for project "xxxx": googleapi: Error 400: Request contains an invalid argument., badRequest.

Assumption : 
IAM Role "roles/owner" requires initating an invitation workflow which results an error through API

**Comment by morgante** [comment]
You can only invite gmail accounts to use the owner role through the Cloud Console: https://cloud.google.com/iam/docs/granting-changing-revoking-access#granting-gcloud-manual

This is Google API limitation, not a Terraform issue.

**Comment by thiagonache** [comment]
it is odd that it does work for folder.....
