### ISSUE TITLE
Provider doesn't support resource: google_compute_subnetwork_iam_member

### ISSUE THREAD

**Issue by ye** [terraform-google-modules/terraform-google-iam#15]
Hi,

I am trying to use terraform and this iam module to create a few service accounts but getting errors:

```zsh
ye@mac $ tf version 
Terraform v0.11.13
+ provider.external v1.1.1
+ provider.google v2.4.0
+ provider.kubernetes v1.6.2

ye@mac $ tf init                                                                                                                                                                                       
Initializing modules...
- module.iam

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.external: version = "~> 1.1"
* provider.kubernetes: version = "~> 1.6"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
 
ye@mac $ tf plan                                                                                               

Warning: google_container_cluster.primary: "zone": [DEPRECATED] Use location instead



Warning: google_container_node_pool.admin_support_pool: "zone": [DEPRECATED] use location instead



Warning: google_container_node_pool.cache_pool: "zone": [DEPRECATED] use location instead



Warning: google_container_node_pool.cron_pool: "zone": [DEPRECATED] use location instead



Warning: google_container_node_pool.stateless_dataprocess_pool: "zone": [DEPRECATED] use location instead



Warning: google_container_node_pool.stateless_pool: "zone": [DEPRECATED] use location instead



Warning: google_container_node_pool.stateless_worker_pool: "zone": [DEPRECATED] use location instead



Warning: google_container_node_pool.support_pool: "zone": [DEPRECATED] use location instead



Error: module.iam.google_compute_subnetwork_iam_binding.subnet_iam_authoritative: Provider doesn't support resource: google_compute_subnetwork_iam_binding



Error: module.iam.google_compute_subnetwork_iam_member.subnet_iam_additive: Provider doesn't support resource: google_compute_subnetwork_iam_member

Error: module.iam.google_compute_subnetwork_iam_member.subnet_iam_additive: Provider doesn't support resource: google_compute_subnetwork_iam_member

ye@mac $ cat svc-acct.tf
data "google_service_account" "foobar" {
  account_id = "foobar-pod-sa"
}

resource "google_service_account_key" "foobar_key" {
  service_account_id = "${data.google_service_account.foobar.name}"
}

resource "kubernetes_secret" "gac_foobar" {
  metadata = {
    name = "gac-foobar"
  }
  data {
    credentials.json = "${base64decode(google_service_account_key.foobar_key.private_key)}"
  }
}
```
So what did I do wrong here?

**Comment by morgante** [comment]
Subnet IAM requires a beta provider to be configured, can you make sure to include a [beta provider block](https://www.terraform.io/docs/providers/google/provider_versions.html#using-the-google-beta-provider)?

**Comment by ye** [comment]
@morgante thanks! that seems to solve this particular error.

**Comment by ye** [comment]
@morgante I encountered another bug today and tweaking the tf files again and realized that the beta provider block you linked there doesn't seem to work.

I forgot where I found the solution but I kinda did what someone suggested here https://serverfault.com/a/935062/186208 to inject a provider in the module calling block. Not entirely sure why it would work but it got pass the `tf plan` validation.

```hcl
  providers = {
    google = "google-beta"
  }
```
So my question again was this: if there a way to disable `google_compute_subnetwork_iam_member` resource definition in this module so that I don't have to worry about juggling with a `google-beta` provider? Or even better yet, can we default to use `google-beta` instead?

**Comment by aaron-lane** [comment]
Hi @ye!

HashiCorp's [recommendation](https://www.terraform.io/docs/configuration-0-11/modules.html#providers-within-modules) is that providers are configured by the root module.

I believe the issue you are experiencing is due to the fact that we have not released any of the changes on the master branch since v1.0.0 in August of 2018. We will publish a new version of this module today and the provider configuration should work as expected, such that you should not need to alias `google-beta` as `google`.

**Comment by morgante** [comment]
@aaron-lane Let's confirm this fixed it before closing.

**Comment by aaron-lane** [comment]
@ye since you continued to experience an issue after closing this issue, we have reopened it for you. [v1.1.0](https://registry.terraform.io/modules/terraform-google-modules/iam/google/1.1.0) has been released. Can you please try using that version to see if your problem is solved?

**Comment by ye** [comment]
thank you @aaron-lane and @morgante I've updated my tf file by removing the providers block hack, it seems to be working fine now (reading from root module, and yes I am 100% onboard with that recommendation!). Now the only bug is the bash script argument error bug I opened in another ticket, but I have a workaround I will test.

I am considering this closed.
