### ISSUE TITLE
base_roles Include All

### ISSUE THREAD

**Issue by SpyderDave** [terraform-google-modules/terraform-google-iam#151]
### TL;DR

It would be nice to be able to use this module in a manner which would allow simply combining multiple roles (base_roles) into a single custom role without the need to specify individual permissions from the base_roles.

Maybe this is possible?

**Comment by morgante** [comment]
This is already possible today. You can leave the permissions list empty if you don't want to add any permissions. Example:

```
module "custom-roles" {
  source = "terraform-google-modules/iam/google//modules/custom_role_iam"

  base_roles           = ["roles/compute.viewer", "roles/bigquery.viewer"]
  permissions          = []
}
