### ISSUE TITLE
Allow referencing computed values

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-iam#4]
As documented [here](https://github.com/terraform-google-modules/terraform-google-iam/blob/ddf319d6fa0fd092a308848dc9584f0fd6b99fd9/README.md#referencing-valuesattributes-from-other-resources), the module currently fails when using computed inputs (such as Service Accounts created by Terraform).

Fixing this has two parts:

- [ ] Allow referencing computed values in the base resource target (ie. `projects`, `folders`, etc.)
- [ ] Allow referencing computed values in the bindings themselves (ex. to reference service account emails)

**Comment by ocervell** [comment]
Any updates here ? This module is very hard to use without referencing values like service account / group / user names / project_id.

**Comment by morgante** [comment]
No current updates - but hopefully Terraform 0.12 will make this easier.

**Comment by coachin2au** [comment]
By my read of the 0.12 release notes, I don't think this has been resolved.  Anyone concur/disagree?

**Comment by morgante** [comment]
Yes, unfortunately that seems to be the case. We might have to break this module out/refactor to fix this.

**Comment by bohdanyurov-gl** [comment]
For this module to support computed values I see only two primary options:
1. Add bunch of "_count" variables (like "folders_count") to use them in count fields
2. Same as 1, but additionally move everything to submodule to make count fields optional (for backward compatibility)

**Comment by aaron-lane** [comment]
I am strongly in favour of breaking this module in to submodules. The root module can maintain the shared logic of generating the bindings structure.
