### ISSUE TITLE
for_each rewrite

### ISSUE THREAD

**Issue by sleterrier** [terraform-google-modules/terraform-google-iam#46]
Hi,

It is still a work in progress, but I have started re-writing this module with _for_each_ to work around the count limitations and avoid bindings re-creation when the input map changes:
https://github.com/sleterrier/terraform-google-iam

I don't think the Issues board  is the best place for this, but I thought you might be interested in seeing this new >=0.12.6 approach.

**Comment by morgante** [comment]
Thanks for sharing. We're also looking at decoupling this module into submodules for each resource type.

When you're ready, we'd be happy to look at a PR.
