### ISSUE TITLE
git source on submodules is not registered and the link is not working

### ISSUE THREAD

**Issue by alekhyal** [terraform-google-modules/terraform-google-iam#55]
git source for submodule projects_iam is not working.
source   = "terraform-google-modules/iam/google//modules/projects_iam"

**Comment by morgante** [comment]
Hi, can you share the Terraform config you're attempting to use?

**Comment by alekhyal** [comment]
Hi, 
here you go - 
Throws an error: **Error: Failed to read module directory**
/******************************************
  Module project_iam_binding calling
 *****************************************/
module "project_iam_binding" {
  source   = "terraform-google-modules/iam/google//modules/projects_iam"
  projects = [var.project_one, var.project_two]
  mode     = "additive"

  bindings = {
    "roles/compute.networkAdmin" = [
      "serviceAccount:${var.sa_email}",
      "user:${var.user_email}",
    ]
    "roles/appengine.appAdmin" = [
      "serviceAccount:${var.sa_email}",
      "user:${var.user_email}",
    ]
  }
}
