### ISSUE TITLE
'Call to function "coalescelist" failed: no non-null arguments ' on terraform import

### ISSUE THREAD

**Issue by bodschut** [terraform-google-modules/terraform-google-iam#56]
Hi,

I'm trying to import existing IAM bindings into the terraform state using this google-iam module. My terraform configuration is as follows:

```
module "main_organization_iam_binding" {
    source = "terraform-google-modules/iam/google"

    organizations = [var.organization_id]

    mode = "authoritative"

    bindings = {
        "roles/resourcemanager.folderAdmin" = [
            "user:user1@test.com",
            "user:user2@test.com"
        ]
    }
}
```

The value for organization_id variable is defined in a terraform.tfvars file. When I terraform plan this config, I see that the resource that will be created for the folderAdmin binding is the following:

```
module.main_organization_iam_binding.google_organization_iam_binding.organization_iam_authoritative[0]
```

So, I try to run the following import statement:

```
terraform import 'module.main_organization_iam_binding.google_organization_iam_binding.organization_iam_authoritative[0]' "<org_id> roles/resourcemanager.folderAdmin"
```

But this generates the following error message:

```
Error: Error in function call

  on .terraform/modules/main_organization_iam_binding/terraform-google-modules-terraform-google-iam-96813bd/main.tf line 53, in locals:
  53:   objects_affected = coalescelist(
  54: 
  55: 
  56: 
  57: 
  58: 
  59: 
  60: 
  61: 
  62: 
  63: 
  64: 
    |----------------
    | var.folders is empty list of string
    | var.kms_crypto_keys is empty list of string
    | var.kms_key_rings is empty list of string
    | var.organizations is empty list of dynamic
    | var.projects is empty list of string
    | var.pubsub_subscriptions is empty list of string
    | var.pubsub_topics is empty list of string
    | var.service_accounts is empty list of string
    | var.storage_buckets is empty list of string
    | var.subnets is empty list of string

Call to function "coalescelist" failed: no non-null arguments.
```

Any ideas on how to make this work?

**Comment by morgante** [comment]
I would actually suggest avoiding importing bindings. Recreating the same binding is a no-op, so once you've mirrored your existing bindings in Terraform you should be good to apply.

**Comment by cciocov** [comment]
@morgante 
This error happens for any import command, not necessarily something to do with IAM bindings. As soon as this module is used, any terraform import command fails.

**Comment by morgante** [comment]
@cciocov Sorry for the delayed response. We have actually switched to resource-specific submodules, could you see if this still happens with the organizations submodule? https://github.com/terraform-google-modules/terraform-google-iam/tree/master/modules/organizations_iam

**Comment by YoSarin** [comment]
I do have almost the same issue with completely different provider (for azure) and coalesce - any import ends up with coalesce inputs being empty.

That being said, i would expect issue is probably somewhere deeper - in terraform itself (or both providers have same issue)
