### ISSUE TITLE
Add separate test suites for additive and authoritative bindings

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-iam#59]
Currently, we have a single test suite with a variable that determines the binding mode and tests which try to accommodate both options. Ideally, we should have separate test suites which are focused on each binding mode.

**Comment by morgante** [comment]
Hmm, this seems like a lot of duplicated code. What's the issue with having both tested using the same fixture?

**Comment by aaron-lane** [comment]
#57 introduces conditional logic in the tests to account for both binding modes, which makes the tests harder to understand. If we redesign the tests to feature two distinct Kitchen instances, we can rely on shared Terraform fixtures and InSpec libraries to address the duplicated code while still providing two obvious points of execution to evaluate the different modes.

**Comment by morgante** [comment]
Got it, that makes sense to me:
1. Two separate test suites
2. Test suites can share some code via libraries
3. Both test suites use the same Terraform fixtures
