### ISSUE TITLE
Documentation and examples update for v3.0.0

### ISSUE THREAD

**Issue by marko7460** [terraform-google-modules/terraform-google-iam#67]
According to 2.0->3.0 documentation, this should work:
```hcl
module "owners" {
  source      = "git@github.com:terraform-google-modules/terraform-google-iam.git?ref=v3.0.0"
  folders_mode  = "additive"
  folders     = [substr(data.terraform_remote_state.folders.outputs.folder_id, length("folders/"), -1)]
  folders_bindings  = {
    "roles/owner" = var.owners
  }
}
```
However i actually had to do:
```hcl
module "owners" {
  source      = "git@github.com:terraform-google-modules/terraform-google-iam.git?ref=v3.0.0"
  folders_mode  = "additive"
  folders     = [substr(data.terraform_remote_state.folders.outputs.folder_id, length("folders/"), -1)]
  folders_bindings  = {
    "roles/owner" = var.owners
  }
  pubsub_topics_bindings = {}
  pubsub_subscriptions_bindings = {}
  storage_buckets_bindings = {}
  subnets_bindings = {}
  subnets_region = ""
  organizations_bindings = {}
  kms_crypto_keys_bindings = {}
  kms_key_rings_bindings = {}
  service_accounts_bindings = {}
  projects_bindings = {}
}
```

If required variables are not set the module will not work.

**Comment by morgante** [comment]
Good point! We missed setting defaults for bindings.

Note that I'd recommend directly invoking the specific resource submodule though. Ex. https://github.com/terraform-google-modules/terraform-google-iam/tree/master/modules/folders_iam

We might end up removing the top-level interface entirely in a future release.

**Comment by aaron-lane** [comment]
Let's update the migration guide and README example with the correct syntaxt, and emphasize usage of the new submodules. We can adjust the migration guide to promote the new submodules first and offer the root module as the alternative.

**Comment by aaron-lane** [comment]
@omazin please take this on.
