### ISSUE TITLE
specifying a single project in projects-iam causes module to do nothing

### ISSUE THREAD

**Issue by ideasculptor** [terraform-google-modules/terraform-google-iam#69]
There is both a project and a projects variable available in the module.  The implication from the docs is that one or the other must be provided.  If you use the former, the module does no work.  It only functions if you specify a list of one project in the projects variable.

**Comment by morgante** [comment]
@cray0000 Please make sure this is fixed in your refactor.

**Comment by cray0000** [comment]
Fixed in #64 

it was indeed an issue even in my fork. Had to rearchitect that option to make it work correctly and not lead to the dynamic behavior.

Also added unit test for it in the `static-and-dynamic` suite.
