### ISSUE TITLE
Warnings of deprecated features in output

### ISSUE THREAD

**Issue by tdigangi** [terraform-google-modules/terraform-google-iam#8]
When running a successful `terraform plan` the following stdout is returned.
 
Warning: module.iam_binding.google_compute_subnetwork_iam_binding.subnet_iam_authoritative: "project": [DEPRECATED] This resource is in beta and will be removed from this provider. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Warning: module.iam_binding.google_compute_subnetwork_iam_binding.subnet_iam_authoritative: "region": [DEPRECATED] This resource is in beta and will be removed from this provider. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Warning: module.iam_binding.google_compute_subnetwork_iam_binding.subnet_iam_authoritative: "subnetwork": [DEPRECATED] This resource is in beta and will be removed from this provider. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Warning: module.iam_binding.google_compute_subnetwork_iam_member.subnet_iam_additive: "project": [DEPRECATED] This resource is in beta and will be removed from this provider. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Warning: module.iam_binding.google_compute_subnetwork_iam_member.subnet_iam_additive: "region": [DEPRECATED] This resource is in beta and will be removed from this provider. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Warning: module.iam_binding.google_compute_subnetwork_iam_member.subnet_iam_additive: "subnetwork": [DEPRECATED] This resource is in beta and will be removed from this provider. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

**Comment by morgante** [comment]
What kind of binding are you attempting to handle? Can you share your Terraform config?

**Comment by reechar-goog** [comment]
I've run into this issue before. It looks like Tony is trying to bind IAM bindings to a subnet. I believe that this is trying to do that is a resource level GCE feature, which is currently in Beta: https://www.terraform.io/docs/providers/google/r/compute_subnetwork_iam.html

**Comment by morgante** [comment]
Thanks, we're going to look into this and add some tests to detect deprecated features.

**Comment by paulpalamarchuk** [comment]
Fixed in [version 2.0.0](https://github.com/terraform-google-modules/terraform-google-iam/tree/v2.0.0)

**Comment by aaron-lane** [comment]
The beta provider is now documented as required.
