### ISSUE TITLE
Feature: Use google-beta provider

### ISSUE THREAD

**Issue by Lirt** [terraform-google-modules/terraform-google-iam#89]
Would it be possible to allow using of `google-beta` provider?

Reason I ask is that IAM policies currently fail due to using newer policy version, which is not available in stable provider (https://github.com/terraform-providers/terraform-provider-google/issues/5218). I would like to specify that I want to use google-beta provider using some variable.

**Comment by morgante** [comment]
Could you try setting a [provider alias](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly)?

```
provider "google-beta" {
  alias  = "gcp-beta"
}

module "example" {
  source    = "./example"
  providers = {
    google = "google-beta.gcp-beta"
  }
}
```

**Comment by Lirt** [comment]
I'm going to test it.

**Comment by Lirt** [comment]
It works fine, thank you.
