### ISSUE TITLE
Support empty map of bindings for all submodules

### ISSUE THREAD

**Issue by imrannayer** [terraform-google-modules/terraform-google-iam#96]
Hi,
We are currently passing in a dynamic list of bindings to the module, which fails when you supply an empty maps of bindings (we have a some projects and folders which don't have any IAM permissions). For example:

module "projects_iam_bindings" {
  source  = "terraform-google-modules/iam/google//modules/projects_iam"
  version = "~> 3.0"
  projects = [google_project.my_project.project_id]
  mode     = "additive"
  bindings = module.iambind.project_bindings
}

module iambind (custom module) may or may not return It would be great if you could pass an empty maps, where you have a codebase which is supplying bindings dynamically.

**Comment by bharathkkb** [comment]
@ChandranshuRao14 this should be similar to how we discussed empty subnets PTAL

**Comment by morgante** [comment]
Indeed, I think we can support this.

**Comment by ChandranshuRao14** [comment]
Hi @imrannayer can you post the error Terraform throws when you pass in an empty map for bindings? After running some simple testing it looks like passing in an empty map to `var.bindings` works as expected

**Comment by imrannayer** [comment]
Found the issue. My helper module was not returning map when nothing to return. Documentation says bindings is required. I thought this is why I am getting error. Can we update document to mention empty map can be passed as an argument?
Thanks for quick response.
